### ISSUE TITLE
Feature Request: Autostart

### ISSUE THREAD

**Issue by igoforth** [hugsy/binja-headless#1]
Please add a function that attempts to autostart the RPyc service as that would enable a lot of really fun automation without having to first open the program manually.

**Comment by redthing1** [comment]
I think you can launch Binja from the command line, and when the plugin loads just start the service?

**Comment by hugsy** [comment]
Can't believe I missed this issue for a year 😞 

> Please add a function that attempts to autostart the RPyc service as that would enable a lot of really fun automation without having to first open the program manually.

I can look into that

**Comment by igoforth** [comment]
I’ve completely forgotten why I submitted this, but i still want it :)

**Comment by hugsy** [comment]
Done, thanks for the suggestion! It is a useful feature. Let me know how it goes
